apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: cluster-a1.k8s.local
spec:
  kubernetesVersion: "1.29.0"
  cloudProvider: aws
  api:
    loadBalancer:
      type: Internal
  networking:
    amazonvpc:
      vpcId: ${aws_vpc.main.id}
      subnets:
      - cidr: ${aws_subnet.public[0].cidr_block}
        name: PublicSubnet1
        type: Public
        zone: ${data.aws_availability_zones.available.names[0]}
      - cidr: ${aws_subnet.private[0].cidr_block}
        name: PrivateSubnet1
        type: Private
        zone: ${data.aws_availability_zones.available.names[0]}
  etcdClusters:
  - name: main
    version: "1.29.0"
    etcds:
    - name: etcd-0
  - name: events
    version: "1.29.0"
    etcds:
    - name: etcd-0
  kubeAPIServer:
    accessStrings:
    - "0.0.0.0/0"
  kubeControllerManager:
    cpuRequest: 100m
  kubeScheduler:
    cpuRequest: 100m
